# Generated by Django 4.2.6 on 2023-10-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
