# Generated by Django 4.2.6 on 2023-11-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_likes'),
        ('users', '0002_profile_online_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='headline',
            new_name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='favourite',
            field=models.ManyToManyField(blank=True, to='post.post'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='profiles/defaudt.jpg', null=True, upload_to='profiles/'),
        ),
    ]
