# Generated by Django 4.2.6 on 2023-10-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatmodel_read_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
