# Generated by Django 4.2.6 on 2023-10-23 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatmodel_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmodel',
            old_name='is_read',
            new_name='is_seen',
        ),
    ]
